#re-run pipeline
name: blmsv1-feature-branch-pipeline
on:
  push:
    branches-ignore:
      - 'main'
      - 'releases**'
jobs:
  build-and-test:

    runs-on: [self-hosted, onprem]

    steps:
      - run : echo "build and test"
